### ISSUE TITLE
Unique columns

### ISSUE THREAD

**Issue by Subb98** [Respect/Validation#1177]
Hi. I need to check the unique column in the table, but in the documents I don't see this method. Is it possible? Or should I call the database in the controller after the middleware (bad resolution for me)?

**Comment by henriquemoody** [comment]
We don't have such a rule because it depends on the project (Relational or Non-relational database, ORM or using the API of the driver directly.

You can create a custom rule for that, that's what I do. See how in the documentation: https://respect-validation.readthedocs.io/en/1.1/feature-guide/#custom-rules
