### ISSUE TITLE
Status of 2.0?

### ISSUE THREAD

**Issue by alystair** [Respect/Validation#1272]
I helped with a UUID validator contrib back in 2018, and was added to master May 12, 2019 -  however v2 is still not released and we'd like to use an updated stable version in production. 

Is there any schedule/time frame for next release?

**Comment by agchan12** [comment]
I am also interested in when the newest version of respect will be released.

**Comment by henriquemoody** [comment]
Hi, @alystair and everyone else.

Today it was the first time this year that I contributed to this project. My last commit was on the 4th of June of 2019. Truth is, my life has changed a lot since then, and it turned out that I had way more interest in other aspects of my life than doing open source. It's been so long that this version is on `master` that I decided to tag it as is. It won't be perfect and there are things I'd like to change, but honestly, done is better than perfect.

**Comment by alystair** [comment]
Hi @henriquemoody - perhaps you create issue and add a notice linking to it in the README that you are looking for a new maintainer for the project so work continues :)

Sadly I'm too busy to take it on.

**Comment by henriquemoody** [comment]
The version 2.0 has been released: https://twitter.com/TheRespectPanda/status/1246559221711286280

I got an email from someone wanting to help, I will reply and see how it goes, however, I'd prefer people who have worked in the library already to just keep it moving.

Thanks for your support, @alystair!
