### ISSUE TITLE
How to overwrite/extend a predefined rule?

### ISSUE THREAD

**Issue by MyIgel** [Respect/Validation#1280]
In v1 with `$v->with('\\My\\Namespace\\Rules', true);` it was possible to overwrite rules (by adding them first, see https://github.com/Respect/Validation/blob/1.1/library/Validator.php#L181), in v2 it seems to be only possible if I write a whole new Factory as it can't be extended because its final? That would be definitely a big mess of copy and pasted code..

Or did I missed something?

**Comment by henriquemoody** [comment]
Hi, @MyIgel! You can see detailed documentation of how that works on version 2.0: https://respect-validation.readthedocs.io/en/2.0/custom-rules/

Let me know if you find any problems you can't solve using the documentation! 🐼

**Comment by MyIgel** [comment]
Thats exactly what i did, the result is
```
^ Respect\Validation\Factory^ {#1539
  -rulesNamespaces: array:2 [
    0 => "Respect\Validation\Rules"
    1 => "My\Namespace\Rules"
  ]
  -exceptionsNamespaces: array:2 [
    0 => "Respect\Validation\Exceptions"
    1 => "My\Namespace\Exceptions"
  ]
  -translator: "strval"
  -parameterStringifier: Respect\Validation\Message\Stringifier\KeepOriginalStringName^ {#1541}
}
```

and that means that, when the the factory iterates over them in `public function rule(...` it uses the `Respect\Validation\Exceptions` namespace first and then my own namespace which results in the problem that I can not overwrite any predefined validations..

**Comment by henriquemoody** [comment]
> ...which results in the problem that I can not overwrite any predefined validations.

Can you tell me a bit about your use case, and what's your necessity on overwriting the standard rules from this library?

**Comment by MyIgel** [comment]
My usecase here is mainly that I want to be able to use the length of strings in max and min commands in some specific cases and some other minor changes to existing validators.
But besides that I would definitely see it as a benefit to be able to overwrite/wrap some of the predefined validators.

**Comment by MyIgel** [comment]
Is that enough to reopen this issue? ;)

**Comment by fritjofbohm** [comment]
Same issue here. Having the Respect rules as `final` classes leads to many, many complications in my codebase. At the moment (with `respect/validation` v1.1) I use several subclassed Respect rules and exception classes. Most of the subclasses are to change the fail messages, some are for minor behaviour changes/extensions.

I did it the subclass way because I needed to have changed messages *everywhere* validation is called in my "framework" code and in the framework's user's code. Custom messages as in https://respect-validation.readthedocs.io/en/2.0/feature-guide/#custom-messages or a custom Translator are not an option for me, because there are many cases of "same rule types, but different messages" in the code.

It works like a charm in `1.1`, but in `2.0` I don't see a proper way to do this with the required flexibility.

Copying the whole class bodies from `respect/validation` would do the trick, but it feels soo wrong. And a custom `StringTypeException` in my eyes is still a `StringTypeException`, which isn't possible with `2.0`.

**Comment by henriquemoody** [comment]
Thanks for all your comments.

### About not allowing to overwrite the rules

The purpose is to avoid confusion. If you find a code-base using version 1.x and there is a rule "email()" failing, you don't really know whether that rule is from Validation or a custom one until you check the implementation of the code. For cases in which you need a _similar_ rule, I think it is not a big deal to have a different name for that specific rule.

### About not allowing to overwrite the exceptions

It's pretty much the same purpose of not allowing to overwrite exceptions. However, the exceptions contain a protected property `$defaultTemplates` and, in a few cases,  a `chooseTemplate()` method.

1. In case you want to change the message, you could use the translator.
2. In case you want to change the message and add more details to it, there will be nothing left in the parent class to use (nor the `$defaultTemplates` nor the `chooseTemplate()`).
3. In case you want to change the `chooseTemplate()`, than please report it here, because that means something is wrong.

### About making small changes to Validation rules

If there is something wrong in a Validation rule, please report the error so everyone is aware of it. But if you wanna make a rule to behave differently, then I think that rule should have a different name

### About classes being final (and properties being private)

That is to help me to maintain this library. Keeping all properties public/protected and allowing classes to be extended is very expensive, because I have to keep backwards compatibility until a next MAJOR release and I can't really trust the properties' values, because they can change anytime.

You can still kinda wrap Validation rules and create your own using `AbstractWrapper` and `AbstractEnvelope`. You can see some examples exist even in this library:

- https://github.com/Respect/Validation/blob/master/library/Rules/Optional.php
- https://github.com/Respect/Validation/blob/master/library/Rules/Roman.php
- https://github.com/Respect/Validation/blob/master/library/Rules/Between.php

Do you think you would be able to solve your problem `AbstractWrapper` and `AbstractEnvelope` and the translator?

**Comment by fritjofbohm** [comment]
Thank you for your detailed answer! This definitely helps to clear things up. Your design decisions make sense, and your hint on using `AbstractWrapper` and `AbstractEnvelope` will definitely help.

**About making small changes to Validation rules**  
I already use a different name, e.g. `AllOfFailing` as a mod of `AllOf` that skips the remaining sub-validations as soon as one sub-validator fails.  
Since I cannot use `AllOf` as a base class any more, copying all of its code for only one added line (a `break;`) looks like my only option. But that will be the bitter pill I have to take when I still want to use your library.

**Comment by henriquemoody** [comment]
I'm happy to hear it helps.

Actually, the `AllOf` is the only class that is not `final`, because `Validation` extends it. And you can access the the inner rules with the `getRules()` method.
