### ISSUE TITLE
Cannot call abstract method 'StaticValidator::allOf' in PhpStorm

### ISSUE THREAD

**Issue by ilkinabd-talk** [Respect/Validation#1362]
After update PhpStorm this error appeared 
Please look at screenshot

![Screen Shot 2021-08-03 at 10 58 54](https://user-images.githubusercontent.com/82504177/127979621-7a92c15d-3c32-4d77-a721-10d1f25796e4.png)

**Comment by sunchuo** [comment]
me too

**Comment by jklee210104** [comment]
Can i solve this issue please?

**Comment by bradxpeters** [comment]
+1

**Comment by russelomua** [comment]
Latest version of PhpStorm is require to implement all methods of interface Respect\Validation\StaticValidator
is to way to fix it: 
1. Write code for all of methods in class
2. Transfer description of methods from interface to DocBlock of Respect\Validation\Validator

i think second way will be prefer, example:
![2021-08-16 132423](https://user-images.githubusercontent.com/313658/129549568-a7ddc168-0175-4c4d-b4e9-687efedce6ec.png)

can make PR

**Comment by russelomua** [comment]
Have some problems with defining union type of argument in DocBlock :( so types not be same as in interface.

**Comment by nkrovex** [comment]
We are waiting for feedback from the repository owner :)

**Comment by alganet** [comment]
I'm willing to help if someone wants to fix this. 

We also need to check if the solutions proposed work on other popular editors such as VSCode. Anyone willing to report how autocompletion behaves over there?

**Comment by esleyalves** [comment]
+1

**Comment by n00dl3** [comment]
I found a [twitter conversation](https://twitter.com/SpantzBayBee/status/1420775597027041284) about this issue. It seems to be an IntelliJ regresion and according to the referenced [ticket](https://youtrack.jetbrains.com/issue/WI-61674),  the issue seems to be fixed with the latest IntelliJ version ( 2021.3).

I now use the latest version ( IntelliJ IDEA 2021.3 Beta (Ultimate Edition)) and I don't experience this issue anymore.


[PhpStorm EAP](https://www.jetbrains.com/phpstorm/nextversion/#section=linux)
[IntelliJ EAP](https://www.jetbrains.com/idea/nextversion/#section=linux)

**Comment by alganet** [comment]
@n00dl3 awesome! Thanks for the investigative work. I'm closing this for now.
