### ISSUE TITLE
My relationship with Validation

### ISSUE THREAD

**Issue by henriquemoody** [Respect/Validation#1370]
Hello, everyone!

I've started to contribute to Respect in 2012. At that time, all the core developers were living together. That made it very fluid and pleasant to share ideas and to work on the Respect components. After we were not living together anymore, I kept on working in Validation, on and off.

As time went by, all of us stopped working on it. It was only in 2014 that I got back to it. I was using Validation more than the other core developers, and it was just natural that I started to maintain it more actively.

With the help of multiple people, I released many minor and patch versions. I released the first major version in 2015, then a minor version in 2016. In 2020, I finally managed to release version 2.0 after years of working on it. 

Validation is awesome! According to Packagist, just in the last 30 days, there were 314k installs and 14k just in the past 24 hours. Hundreds of public GitHub projects use Validation as their dependency.

I've spent many hours working on Validation over the years. However, I haven't spent much time on it as would be needed to keep it alive. It doesn't help that I'm not using it at work since the company I work for already has a specific stack and does data validation using a full-stack framework.

The truth is, though, that I haven't had much energy to keep working with it anymore. I want to spend my time doing things that bring me joy. It's been a while that Validation doesn't fit that criteria.

I'm writing this message because I think that's the least I can do for all the users and contributors of Validation. I have had people sending me emails to ask me for my participation. I even got an email of someone offering to take care of the library, but I didn't feel comfortable giving writing privileges to someone who has never contributed to it.

I won't be working on Validation anymore. Maybe I will send a pull request or reply to an issue here and there. I'm not the only core developer, of course, it's not like the library will die! I'm just stating that I won't be actively working on it anymore.

Thanks to everyone that helped me to keep Validation as the most awesome validation engine ever created for PHP!

**Comment by alganet** [comment]
Thanks for everything @henriquemoody!

**Comment by danilocorrea87** [comment]
@henriquemoody you were amazing !!! 

I learned a lot when you helped me to contribute to the project.

**Comment by nickl-** [comment]
@henriquemoody he'll be back

**Comment by jasonkhanlar** [comment]
I'm writing a MediaWiki extension that provides a JS Gallery library to wiki pages, currently writing a isConfigKeyValid() PHP function for a class to check if user designed configuration key/value pairs are valid for each different key possible values. I'm looking for a PHP library useful for handling this instead of writing my own, and stumbled upon this. Otherwise in Libera.chat/PHP someone suggested https://github.com/symfony/validator but that appears to be based on Java, and immediately I started looking elsewhere for better alternatives. I noticed a few issues regarding inconsistent exception messages, etc., and hopefully a fluid and pleasant team can be restored to continue maintaining an awesomely useful (it appears so) library that I think I want to use.
