### ISSUE TITLE
Use only Respect\Validation exceptions instead of native ones

### ISSUE THREAD

**Issue by henriquemoody** [Respect/Validation#260]
There is some places we are using native SPL exceptions and it's great but users cannot know when the exception is ours or not.
We can keep using SPL exceptions but also having our own exceptions.

**Base Exception interface**
```php
namespace Respect\Validation\Exceptions;

interface ExceptionInterface
{
}
```

**ValidationException**
```php
namespace Respect\Validation\Exceptions;

use InvalidArgumentException;

class ValidationException extends InvalidArgumentException implements ExceptionInterface
{
}
```

**ComponentException**
```php
namespace Respect\Validation\Exceptions;

use Exception;

class ComponentException extends Exception implements ExceptionInterface
{
}
```

etc..

**Comment by AndyWendt** [comment]
Just so that I am on the same page as you as to what modifications need to be done.  It appears to me that we need to:

* README.md 
    * Change `catch` wherever SPL exceptions are used to reference the custom exceptions `\Respect\Validation\Exceptions\<SPL_EXCEPTION_NAME>`
* Add a new class only for SPL exceptions that are used in the code
* Change Test Cases to catch our new Exceptions
* Change the current `Respect\Validation\Exceptions` to use the new exceptions
    * e.g. Change `Respect\Validation\Exceptions\ValidationException` to extend `\Respect\Validation\Exceptions\InvalidArgumentException` instead of `\InvalidArgumentException` 

It looks like you are dynamically throwing the exceptions so we don't have to modify the rules files most likely.

If this is what you want I will submit a PR with the changes.

**Comment by henriquemoody** [comment]
Go for it!

Currently, the code we have only throws `ComponentException` or the specific rule exception, both are from Respect\Validation but there is no common type, like `Respect\Validation\Exceptions\ExceptionInterface` which was proposed.

**Comment by henriquemoody** [comment]
I've updated the issue description.

**Comment by AndyWendt** [comment]
The common type is a great idea and I saw what you were doing with that.  

Because of the inheritance chain, I will only have to change a couple of files unless you would like me to change all of the exception classes to implement `Exception` or `ExceptionInterface` (whichever you would like to call it).

**Comment by henriquemoody** [comment]
Actually there is only those two exceptions classes: `ValidationException` and `ComponentException`; all others use inheritance from them, so change those two is enough for a while.

`ExceptionInterface` is the correct name according to [PSR naming conventions](https://github.com/php-fig/fig-standards/blob/master/bylaws/002-psr-naming-conventions.md).

**Comment by alganet** [comment]
Please note that these are conventions for code released by the FIG, not code written in PSR-2. We can keep the same style for interfaces (any adjective) if we want.

**Comment by henriquemoody** [comment]
I know that, @alganet, that's why I didn't mentioned _PST-X_.
Whatever, I think better we use them instead of having our own, but we can have our own if you wish so.

**Comment by AndyWendt** [comment]
I personally think it is weird to append `Interface` onto the end of a 
type name (or prepending `I` as is the convention in C#).

But I also see the point of following standards *especially in a widely 
used package.*

Which PSRs do you want this package to follow?  I can update ` 
CONTRIBUTING.md 
<https://github.com/Respect/Validation/blob/master/CONTRIBUTING.md>`, if 
you like, so that others will know.

**Comment by henriquemoody** [comment]
Me too, @AndyWendt. I don't like it as much I don't like to put `Abstract` in the beginning of abstract classes, but since it's a widely used standard I think better we do it.
