### ISSUE TITLE
Problem validating objects

### ISSUE THREAD

**Issue by konstantinrachev** [Respect/Validation#268]
Hi Respect/Validation guys,

I am trying to validate a stdClass (object) attributes, however the check message still comes to: Not\-Attribute Province must be present.
However the Province attribute is set, the dump of ```isset($Obj->Province)``` equals to true.

```php
$Obj = new stdClass;
$Obj->Province = 10;

$Validator = v::attribute('Province', v::numeric()->positive()->notEmpty());
if ($Validator->validate($Obj) == true) {}
```

**Comment by henriquemoody** [comment]
I did run the same code:

```php
$Obj = new stdClass;
$Obj->Province = 10;

$Validator = v::attribute('Province', v::numeric()->positive()->notEmpty());
if ($Validator->validate($Obj) == true) {
    echo 'Object is valid!'.PHP_EOL;
}
```
I got no error and I could see _"Object is valid!"_.

I'm using OSX Yosemite, with PHP 5.6.4 and I have tested tested versions `0.5.0`, `0.6.0` and `0.7.0`, what are you using there?

**Comment by konstantinrachev** [comment]
I'm running Ubuntu 14.10, with PHP 5.6.3 and tested on 0.7.0 and 0.8.0(both dev versions).

**Comment by henriquemoody** [comment]
@konstantinrachev, I have created a PHPT test, as you can see on commit 38f8263 (tests results are available on [Travis](https://travis-ci.org/henriquemoody/Validation/builds/48419725)) and I could not reproduce this error.

Another awkward thing I just saw was the message _"Not-Attribute Province must be present"_. The right message should be `Attribute Province must be present` and only when you use `check()` method. Are you sure this is the same code or if is there some change on you Respect\Validation installation?

Even though, if you're sure it's a bug on Respect\Validation, and since you can reproduce this bug in your environment it's going to be awesome if you send a pull requests with this fix.

**Comment by henriquemoody** [comment]
@konstantinrachev, I close this issue because I see no point of keeping it opened, but feel free to reopen it if you think it's necessary
