### ISSUE TITLE
Install this library without Autoload etc.

### ISSUE THREAD

**Issue by tomew** [Respect/Validation#321]
How installing your library without any autoloader in a clean way?

Thank you

**Comment by henriquemoody** [comment]
We use to have PEAR and PHAR support, but we dropped this support and looks like people doesn't care too much about it.

So, we really rely on autoloader, and the main method to install all Respect components is by Composer.

**Comment by tomew** [comment]
That isn't great. I do not like that -_-

Is it mad when I made this project by my own just because I was too lazy to find a nice way to implement your library into my project? If yes, hit me. Thank you anyway :)

**Comment by henriquemoody** [comment]
@tomew, can you explain why you don't want to create an autoloader for that or even use Composer? Perhaps I just didn't get what you need.

**Comment by tomew** [comment]
I think I am too lazy for this. Composer is too new for me, never worked with it and I do not think that I wanna change with my current project to this (?) you know, I have no idea about it.

And of course, I have a Autoloader but I think it is not fimiliar with your Namespace-Names and my way how I included the files then.

**Comment by henriquemoody** [comment]
There are many way to do it, even using only shell script (`find library -name '*.php' | xargs -I% echo  "include_once __DIR__.'/%';" | cat > poor_class_map.php`) but I strongly recommend you to try Composer, it will surely help you in any project.

Tell me if you need anything.

**Comment by augustohp** [comment]
> I think I am too lazy for this. Composer is too new for me

You don't need composer to use the library. It makes easier, but it is not required.

> I do not think that I wanna change with my current project to this (?) you know, I have no idea about it.

You are going to, since you ignored conventions and went you own way doing things. It is not wrong to do that, but expecting things would just "work out" for you with 3rd party libraries without any boiler-plate code is a naive assumption to have.

Fortunately for you, you just need to implement a [PSR-4][2] compatible [autoload][1] function and you will be ready to go. Not only on using "Respect" components but probably ano other on [Packagist](packagist.org/).

> And of course, I have a Autoloader but I think it is not fimiliar with your Namespace-Names and my way how I included the files then.

You [can register multiple autoload functions][1] and we use a [very widely adopted namespace name convention][2] which you can see [declared on `composer.json`][3]. Implementing it should be as [easy as using this 10 line function][4].

[1]: http://php.net/spl_autoload_register
[2]: http://www.php-fig.org/psr/psr-4/
[3]: https://github.com/Respect/Validation/blob/0.8/composer.json#L31
[4]: https://github.com/Respect/Loader/blob/master/library/Respect/Loader.php#L7-19

**Comment by davidjnelson** [comment]
this approach as suggested by another user on a different thread works well: "use composer on your local development machine and just upload the files after you do a composer install/update"
