### ISSUE TITLE
no php docs, why?

### ISSUE THREAD

**Issue by cofirazak** [Respect/Validation#366]
It's very comfortably when in the IDE you choose a quick documentation for a method from a component and you see a description on how to use the method and what it returns. It's provided by php docs, but i see no php docs in this component. Why?

**Comment by henriquemoody** [comment]
I think it is a habit for us, maintainers. In many discussions I had with the other guys we always agree that's is not necessary, since code must be self-explanatory and when you have a documented you must be careful on change the code and forget the doc and vice-versa. IMO, many cases when you document code you're already duplicating things.

However, we agree that people who use IDE should be more comfortable, so it s already on our plans to increase the documentation. IMO we must document at least the return types and arguments' types.

I will close that because it's a duplicated of #225.

Thanks for reporting.

**Comment by cofirazak** [comment]
Thank you!
