### ISSUE TITLE
numeric not accepting an empty string.

### ISSUE THREAD

**Issue by krazyjakee** [Respect/Validation#381]
> All validators treat input as optional and will accept empty string input as valid, unless otherwise stated in the documentation.

`v::numeric()->validate('') = false`

This makes me a sad panda.

**Comment by henriquemoody** [comment]
That's making me a sad panda for a long time, I must say (#154, #173, #196, #205, #235, #244, #336).

As a workaround you can use:

```php
v::when(v::notEmpty(), v::numeric(), v::alwaysValid())->validate('')
```

I'm sorry because I can't give you more than that for now, but I'm working on a new version where we can fix that for good.

I want to take this opportunity to ask you to answer some pool here, can you see https://github.com/Respect/Validation/pull/173#issuecomment-107801471?
