### ISSUE TITLE
Respect\Validation Truck Factor

### ISSUE THREAD

**Issue by gavelino** [Respect/Validation#382]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Respect\Validation** and obtained a value of **2**.

The developers responsible for this TF are:

Alexandre Gaigalas - author of 46% of the files
Henrique Moody - author of 27% of the files

To validate our results, we would like to ask **Respect\Validation** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Respect\Validation**?

(b) Do you agree that **Respect\Validation** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Respect\Validation** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by henriquemoody** [comment]
The _responsible_ people for this project, as many other ones as well, cannot be measured by the number of commits. If you opened this issue a month ago Nick Lombard would be the second at the list but he doesn't show up since April, 2014, also the latest 4 commits from Alexandre Gaigalas were in January.
In the other hand there is also Augusto Pascutti who plays an important role in this project, answering questions, filtering issues, reviewing pull requests and participating on decision process, but he has only 14 commits on this project.

> (a) Do you agree that the listed developers are the main developers of **Respect\Validation**?

Yes, but I think Augusto Pascutti should be in that list too.

I see myself as the main developer of Respect\Validation since January, but Alexandre Gaigalas, as the creator of the library is, and always will be, the main developer of this library and I always will try to reach him and Augusto Pascutti before make drastic changes.

> (b) Do you agree that **Respect\Validation** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

Yes and it almost happens.

The problem is the access to the repositories, servers and other related thinks like the Packagist, Travis, Scrutinizer. Of course a person can create a fork and start to develop from that fork but I think the project dies before that.

> (c) Does **Respect\Validation** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Yes, some.

We use [lazy consensus](https://rave.apache.org/docs/governance/lazyConsensus.html) so we do not depend so much of each other, basically we can change anything we want if nobody says "No" until 72 hours.
We also have a [Contributing](https://github.com/Respect/Validation/blob/master/CONTRIBUTING.md) page which explains the required steps to create a new rule.

I don't thing that's enough but I don't see how we could do better now, maybe we should increase the number of people with access to the repository but they must be interested on that in the first place. We have 9 people on Respect organization but I see just a few of then participating, it's complicated. See, this issue was opened 2 days ago and I was waiting for someone to answer that and I had to do it myself...

***
I think I answer your question, if anyone wants to say anything else, feel free.

**Comment by gavelino** [comment]
Hi @henriquemoody ,

thanks for the answer. The research is under development and was not published yet.
