### ISSUE TITLE
assert and empty

### ISSUE THREAD

**Issue by Zyles** [Respect/Validation#393]
I use assert but I have empty parameters which I want to be optional and it throws an exception even tho I don't have notEmpty()... can I use optional fields with assert?

Sample code:
```
$validator = v::arr()
			->setName('parameters')
			->key('providerId', 	v::int()->setName('providerId'))
			->key('type', 		v::alnum()->setName('type'))
			->key('amount', 		v::int()->setName('amount'))
		);

		try {

			$validator->assert($params);

		} catch(NestedValidationExceptionInterface $e) {
			throw new \Exception($message, Codes::HTTP_NOT_ACCEPTABLE);
		}
```

I get error such as "Key providerId must be present" ...

**Comment by henriquemoody** [comment]
That's because the `key()` validator checks if the key exists before apply the validator.

You can use the third parameter of this rule to avoid the key checking. Take a look on the documentation: http://respect.li/Validation/docs/key.html.

Your code must be something like this:

```php
$validator = v::arr()
    ->key('providerId', v::int()->setName('providerId'), false)
    ->key('type', v::alnum()->setName('type'), false)
    ->key('amount', v::int()->setName('amount'), false)
);
```

Ps.: In the next version (to be released at Oct 24th) you won't need to use `setName()` on the key rules.
