### ISSUE TITLE
Email validator does not accept certain valid emails

### ISSUE THREAD

**Issue by bartdeman** [Respect/Validation#624]
E-mail addresses like test@localhost are not accepted by the email validator:

v::email()->validate("test@localhost") returns false, while this is actually a valid e-mail address and should return true. The dot in the domain name is not required by the specification.

https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address

**Comment by quantumpacket** [comment]
I agree we should follow the spec, but allowing the spec to be used for typical emails would result in a lot of *invalid* emails when it comes to not wanting local emails to be included.

Maybe have a flag so we can allow such emails when the need arises, but it should default to requiring at least 1 dot otherwise.

**Comment by henriquemoody** [comment]
Our `email()` rule uses PHP's `filter_var()` function with `FILTER_VALIDATE_EMAIL` constant, it provides a very basic email validation. Although we're integrated with [`egulias/email-validator`](https://github.com/egulias/EmailValidator), so if you just install it by Composer  (`composer require egulias/email-validator`) you're going to have a much better validation.

**Comment by bartdeman** [comment]
Thanks for the info.
