### ISSUE TITLE
v::keySet() exception message for required keys could be clearer

### ISSUE THREAD

**Issue by oschwald** [Respect/Validation#628]
Currently, if you have the rule:

``` php
        v::keySet(
            v::key('accept_language', v::stringType(), false),
            v::key('ip_address', v::ip(), true),
            v::key('user_agent', v::stringType(), false)
        )
```

and you validate an array with `ip_address` missing, you will get the exception message `Must have keys { "accept_language", "ip_address", "user_agent" }`. This does not make it clear that only `ip_address` is required and the other keys are optional.

**Comment by thibaudcolas** [comment]
In my testing, this makes `keySet` completely unusable when you rely on error messages as part of your UI: there is no way to map this error message into something end users can rely on.

If it said:

- Key `ip_address` is missing
- Key `whatever_example` is extra

… then that could be converted to a "required" message for end users, and the "extra" message can be  useful to API clients.

The workaround is to use `v::key` only, but then there is no way to validate for extra keys.

**Comment by henriquemoody** [comment]
There are 4 scenarios to consider in `KeySet` would work:

1) `KeySet` failed because there are missing required keys in the input -- that's what I think @oschwald's case is;
2) `KeySet` failed because there are extra keys in the input;
3) `KeySet` failed because there are missing required keys and extra keys;
4) `KeySet` passed the structure check, and delegates the validation to the child `Key` rules.

The case 4 doesn't matter for `KeySet` because it's not its responsibility, and the current message is fine if we're talking about the case 3, but for case 1 and 2 I agree we need to twig that a little bit.

I was a bit confused whether that would be a bug or not, but thinking now I think those things need to be implemented in another version, so I'm putting it in the milestone for the next version. Pull requests are appreciated!

I'm sorry by the delay. But thanks for reporting! 🐼

**Comment by alystair** [comment]
I faced this today, as well as no easy way to tell the validation failed because there were extra array keys that did not have a validator.

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
