### ISSUE TITLE
 Fatal error: Uncaught exception 'Respect\Validation\Exceptions\ComponentException' with message '"string" is not a valid rule name' in /home/navid/workspace/search-engine/src/libs/search/vendor/respect/validation/library/Validator.php on line 209

### ISSUE THREAD

**Issue by nm10** [Respect/Validation#633]
Hi, Every time when i update my composer.json to install some new packages required, Respect tends to behave weird and stop working.

Error Produced are as follows:
Fatal error: Uncaught exception 'Respect\Validation\Exceptions\ComponentException' with message '"string" is not a valid rule name' in /home/navid/workspace/search-engine/src/libs/search/vendor/respect/validation/library/Validator.php on line 209

( ! ) Respect\Validation\Exceptions\ComponentException: "string" is not a valid rule name in /home/navid/workspace/search-engine/src/libs/search/vendor/respect/validation/library/Factory.php on line 56

 Respect\Validation\Exceptions\ComponentException: "string" is not a valid rule name in /home/navid/workspace/search-engine/src/libs/search/vendor/respect/validation/library/Validator.php on line 209

Can you guys help in this case?
Thanks

**Comment by henriquemoody** [comment]
hi, @nm10.

You should be careful when upgrading a MAJOR version because it can really break the API.

On Oct 24 we released a new version of Respect\Validation and we renamed `string()` to `stringType()` in order to allow people to use this library on PHP7.

You can see the full list of changes here: https://github.com/Respect/Validation/wiki/Respect%5CValidation-1.0
