### ISSUE TITLE
How to get custom messages when using keyNested function

### ISSUE THREAD

**Issue by sebenik** [Respect/Validation#635]
Suppose we have a nested class like this:

```
$foo = new stdClass;
$foo->bar->min = -1;
$foo->bar->max = -1;
$foo->baz->min = -1;
$foo->baz->max = -1;
```

And we define a validator using keyNested function:

```
$inputValidator =
    v::keyNested('bar.min', v::numeric()->between(0, 1, true))
    ->keyNested('bar.max', v::numeric()->between(0, 2, true))
    ->keyNested('baz.min', v::numeric()->between(0, 3, true))
    ->keyNested('baz.max', v::numeric()->between(0, 4, true));
```

Is it possible to get a custom message for each specific nested key although its name is not unique? Something like this (this is not working, errors array contains empty strings, while getMessages contains all errors):

```
try {
    $inputValidator->assert($foo);
} catch(NestedValidationException $exception) {
    $errors = $exception->findMessages(array(
        'bar.min' => "custom bar.min message",
        'bar.max' => "custom bar.max message",
        'baz.min' => "custom baz.min message",
        'baz.max' => "custom baz.max message"
    ));
    print_r($exception->getMessages());
    print_r($errors);
}
```

**Comment by henriquemoody** [comment]
I'm not 100% sure, but I think it was fixed by #957.

I've changed how `getMessages()`, check out [get_messages.phpt](https://github.com/Respect/Validation/blob/master/tests/integration/get_messages.phpt) and [get_messages_with_replacements.phpt](https://github.com/Respect/Validation/blob/master/tests/integration/get_messages_with_replacements.phpt) to see how it works.

It will be released with the version 2.0. If any of you want to speed things up take a look at #921!

I'll close this issue, if that was not what you meant, I will reopen it!

Thanks for reporting! :panda_face:
