### ISSUE TITLE
Extention exclude

### ISSUE THREAD

**Issue by hmacube** [Respect/Validation#636]
How can I define rule of exclude extensions?

``` php
$validator = Validator::attribute('extension',Validator::not(Validator::extension(['php','html','js'])));
```

not working because above rule is not(PHP or HTML or JS) and .php extension is valid because of "OR"

**Comment by batusa** [comment]
hi @hmacube , I know it's too late but I'll try to answer it anyway :)

currently, the `Extension` rule accepts only one string parameter which represents the extension. in order to create "a list" of extension that are not allowed, you can do something like that:

```php
<?php

use Respect\Validation\Validator as v;

$data = ['filename' => 'image.jpg'];

v::key('filename', v::not(
    v::oneOf(
        v::extension('php'), 
        v::extension('js'), 
        v::extension('html')
    )
))->validate($data);
```

the validation above would return `true` because JPG is not PHP or JS or HTML.

**Comment by henriquemoody** [comment]
I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for all your comments! 🐼
