### ISSUE TITLE
Sanitizing/Filtering input

### ISSUE THREAD

**Issue by salarmehr** [Respect/Validation#659]
Is there any plan to provide more facilities to sanitize/filter input before validating similar to `Zend_Filter_Input` and adding custom filters beyond `FilterVar`?

**Comment by henriquemoody** [comment]
This has been discussed before on #35 and #115, but we ended up doing nothing with that.

I don't think that's what this library intents to do, since it's a _validation_ library. Although, if you're looking for something similar to what Validation does but with filters, I've wrote this package: https://github.com/PHPFluent/Filter 

Maybe that would help you, but if you have some specific idea about how to implement filters in this library we're opened to discussion. :panda_face:

**Comment by henriquemoody** [comment]
Hope I have answered your question. :)
