### ISSUE TITLE
Key valition always returning false

### ISSUE THREAD

**Issue by aldrinmagno** [Respect/Validation#702]
Hello,

Sorry for the stupid question but I really do not know where to go now.

I had been trying to figure out how to make respect/validation work all day but have not have any luck. Currently I'm using Slim Framework.

I have manage make some of the function work but when I try to use Key to validate my arrays its always returning false.

Here is my code

$post = $request->getParsedBody(); // this gets all of the user input

$userValidator = $this->v->key('txtEmail', $this->v->email()); 

var_dump($userValidator->validate($post)); // this returns false for some reasons

Can anybody help me?

Thanks in advance.

**Comment by henriquemoody** [comment]
Keep in mind that every `v::rule()` creates a new object. What you're doing (apparently) is reusing the same object, `$this->v`, so, in the second call you're adding to the chain `email()`. 

What you're entire chain is saying is: a value with a key `txtEmail` that's also an email, which is impossible because values with keys (arrays or ArrayAccess) can't be also emails.

You should try:

```php
$userValidator = v::key('txtEmail', v::email());
```

Or 

```php
$userValidator = v::create();
$userValidator->addRule(new Key('txtEmail', new Email());
```
