### ISSUE TITLE
String validator and utf-8 symbols

### ISSUE THREAD

**Issue by rzmz** [Respect/Validation#761]
Hi, awesome package, I just cannot understand, why does the string validator not work with utf-8 symbols. For an example: this does not validate as correct string:

v::alnum()->validate('müstika');

but this does: 

v::alnum()->validate('mystika');

can I somehow make the first string validate or is this something that cannot be done with this package?

**Comment by rzmz** [comment]
PS: I have set the correct locale but my problem is that sometimes users with a specific locale want to input characters from another locale. Anyhow, apreciate your help.

**Comment by henriquemoody** [comment]
I created #762 in order to fix this issue.

However, before I merge it I would like to understand in which scenario do you intent to use this validator?

**Comment by henriquemoody** [comment]
Now is more clear what is the intention here.

According to [Wikipedia](https://en.wikipedia.org/wiki/Alphanumeric):
> Alphanumeric is a combination of alphabetic and numeric characters, and is used to describe the collection of Latin letters and Arabic digits or a text constructed from this collection.

That said, the one we have is correct, and changing it would make it wrong. What is needed is a new rule, with a new name and a new purpose. I'm planning to finish it this week, and I'm gonna make it more clear on the documentation. The rule will be probably called _Name_ but I'm very open for suggestions.

**Comment by Hirbod** [comment]
Any news on this? "Name" would be perfect on this, I also reverted to "stringType" which is actually not really correct for this purpose.

**Comment by nickl-** [comment]
Closed: as per #762 Won't fix

**Comment by zefj** [comment]
So how are we supposed to do that?

**Comment by henriquemoody** [comment]
I wrote a comment describing better what's the problem here: https://github.com/Respect/Validation/pull/817#issuecomment-424098285

I'm afraid that you need to build your custom validation, for example:

```php
v::stringType()->notEmoji()->not(v::punct())->validate()
```

But as I said, that depends a lot on what do **you** consider as a valid name.

**Comment by zefj** [comment]
Resorted to regex. I don't particularly like it because of difficulties in communicating the validation error to the front-end, but then again that's the case with pretty much this entire library so I guess I'll just deal with it.

W dniu śr., 6.03.2019 o 16:50 Henrique Moody <notifications@github.com<mailto:notifications@github.com>> napisał(a):

I wrote a comment describing better what's the problem here: #817 (comment)<https://github.com/Respect/Validation/pull/817#issuecomment-424098285>

I'm afraid that you need to build your custom validation, for example:

v::stringType()->notEmoji()->not(v::punct())->validate()

But as I said, that depends a lot on what do you consider as a valid name.

**Comment by henriquemoody** [comment]
I understand, unfortunately it's very difficult to find a perfect solution.

Do you have any suggestions or what are your expectations regarding this
issue and the whole library program?
