### ISSUE TITLE
Contribution for CodeIgniter 3. Integration

### ISSUE THREAD

**Issue by imsajjid** [Respect/Validation#788]
Can you specify the usage of the Library in Codeigniter Framework?

**Comment by henriquemoody** [comment]
Would be nice to have it, but keep documentation of integration with other frameworks would be too much work, specially because I have no idea of how many are out there. For example, I've never worked with CodeIgniter.

However, good luck with this integration! I recommend you to write an article about it if you could integrate them. 🐼
