### ISSUE TITLE
countryName validator with translation

### ISSUE THREAD

**Issue by moutew** [Respect/Validation#804]
Hi,

wondering if a country name validator would be a good one.
I've found country list with translations in 563 locales here 
[https://github.com/umpirsky/country-list](https://github.com/umpirsky/country-list
)
Can be a good starting point, will need some data manipulations as the whole repo is 75Mo uncompressed (lot of formats php, json, ...). Only php files are 6Mo. And there may be lot of redondancy.

What do you think about it ?

**Comment by henriquemoody** [comment]
We already have the list in English, we just don't use it.

I'm not really sure, because there is not standard for country names, creating a validation for it would be very error-prone.

**Comment by moutew** [comment]
I might have developped my use case so maybe you have an easiest way to do. 
I'm using the postalCode validator wich needs a countryCode as a parameter to operate. One is a default in my app config file.

As my app tries to be designed with 'internationalization' in mind, I'm registering adresses wich doesn't assume a country code. But let's imagine someone has to register a customer from another country. To validate the postal code I will need the country code. I don't imagine a user filling this information in a web form. They will fill their country name, in their own language. As the country name might not be in English, it will be hard to find the country code ...

That's why I thinked about this validator.
Another solution would be to let them select their country in a dropdown box wich will be in english.

**Comment by henriquemoody** [comment]
What you can do is display a `<select>` with a list of country names but having the countries' code as `value`s.

Example:
```html
<select name="country_code">
   <option value="BR">Brazil</option>
   <!-- More options here... -->
</select>
```

If your supports internationalization, then you translate the country names and show it according to the user's chosen language.

When the user chose the country by name you'll have the a country code you can use. Then you can even use `v::keyValue('postal_code', 'postalCode', 'country_code')->validate($_POST)`, meaning `$_POST['postal_code']` is a [PostalCode](http://respect.github.io/Validation/docs/postalcode.html) of `$_POST['country_code']`.

See [KeyValue](http://respect.github.io/Validation/docs/keyvalue.html) for more information.

***
I'm closing this issue since the validator doesn't seem to be really relevant for the library, but feel free to comment any time.
