### ISSUE TITLE
Custom template for callback validator as a second parameter

### ISSUE THREAD

**Issue by rkyoku** [Respect/Validation#837]
Hi,

I saw this ticket: #4 but I'm really sorry that I do not find the solution particularly efficient:

- It only works for assert(), not check(), and I, for example, am only using check()
- It does not work for multiple callback validators, except if you use a trick to get it working as described in #800 

I humbly think that the solution proposed 6 years ago, which is attaching a custom template by adding an (optional) second parameter to the callback() validator is the most elegant, intuitive, and bulletproof solution.

Please advise?

Best regards,

**Comment by henriquemoody** [comment]
@rkyoku I'm very sorry it took so long and you didn't get any reply on your issue. It sucks but sometimes it happens. I'm gonna close this issue because it's very old and I have reasons to believe that you've moved on.

I hope you found a resolve for your problem anyways, and feel free to open new ones at anytime and hopefully it will not take a year for somebody to reply! 🐼
