### ISSUE TITLE
[Idea] Error message handling

### ISSUE THREAD

**Issue by Iazel** [Respect/Validation#847]
Hello!
I really like this library, however it looks like error messages are a serious issue for lots of people; after a quick look at issues, many of them regards error messages and someone don't want to use this awesome validator just for that ^^"

So, I would like to discuss with all the community if the follow solution (for which I can do a PR) would be acceptable or not.

Instead of using Exception, I think would be better to return the actual errors, but given that I don't want to break current contract, I lean more on introducing a new method on AbstractValidator, something like:
```
public function getErrorsFor($input): ?array
```
As the name suggest, it should return an array of errors, possibly scoped by either name or input value.

## Example
```
$errors = v::key('name', v::stringType()->notEmpty()->length(2, 40))
           ->key('age', v::intType()->between(18, 30))
           ->key('address', v::keySet([
              'street' => $this->stringType()->notEmpty(),
              'number' => $this->stringType()->notEmpty(),
           ])
           ->getErrorsFor([
               'name' => '',
               'age' => 10,
           ]);
```
The return value could be something like:
```
[
    'name' => [
        ['rule' => 'notEmpty'],
        ['rule' => 'length', 'extra' => ['min' => 2]],
    ],
    'age' => [
        ['rule' => 'between', 'extra' => ['min' => 18, 'max' => 30]]
    ],
    'address' => [
        'street' => ['rule' => 'notEmpty']
        'number' => ['rule' => 'notEmpty']
    ]
]
```
Given this amount of information, it would be rather easy to make any kind of error message. It is particularly handy when we want to send this info to frontend and render the real message there :)

### Normal Rules
Validating a normal rule should return just one array with keys:
* rule: rule's type, like length, between, etc... Always present.
* ruleName: present only if a name is set through `setName`
* extra: an optional array with extra information useful for constructing the error message, eg: `min`

### Composite Rules
Every rules that extends `AbstractComposite` should aggregate all errors returned by each children rules. The result should be an array indexed by child name.
It should support multiple nesting levels.

**Comment by thibaudcolas** [comment]
Here are specific issues that make this library very hard to use when you want to display useful error messages to end users:

- #628 `keySet` throws an error if a key is missing, but doesn't mention which key it is.
- #769 `allOf` (and `each` as well I think) throw their own errors "All of the required rules must pass" when more than one of their sub-validators throw an error. Those extra messages don't add any value to whoever looks at the message.
- #924 default error messages do not provide much context

Looking at the bigger picture, I think the fundamental problem is that (good) error messages seems to be an afterthought for the library. This shows in the documentation, where none of the rules have their error messages documented, and things like [`setName`](https://respect-validation.readthedocs.io/en/1.1/feature-guide/#validator-name) are only briefly mentioned even if they are fundamental to building good messages. Because of this, at the moment the only way to build useful messages for any non-trivial validation is a painful exercise of trial and error.

**Comment by henriquemoody** [comment]
In the next version things will be a little bit easier when trying to get all the error messages, see:

- [get_messages.phpt](https://github.com/Respect/Validation/blob/master/tests/integration/get_messages.phpt)
- [get_messages_with_replacements.phpt](https://github.com/Respect/Validation/blob/master/tests/integration/get_messages_with_replacements.phpt)

However I have to admint that I miss a method like that as well. I have quite some ideas for the version 3.0 (one after the one that is on now), I even created a `Validation` class, see https://github.com/henriquemoody/Validation/commit/b350a17c98ce692449570b795cc12a7766100d89

My idea is that it works like that:

```php
$validation = $rule->validate($input);
$validation->isValid(); // returns TRUE or FALSE
$validation->getMessages(); // returns an array with the messages (key => value)
$validation->getRootMessage(); // returns the message on the top of the chain
$validation->getMainMessage(); // returns the message that broke the validation
$validation->getFullMessage(); // returns a full message with all the broken validation
```

However there is still a lot to do there, I think I'll try to do something for the 2.0. What do you think about the code above?

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
