### ISSUE TITLE
php stream wrapper/PSR-7 and file size validator

### ISSUE THREAD

**Issue by xandros15** [Respect/Validation#852]
The filesize validator has a problem with php streams:
`` SplFileInfo::getSize(): stat failed for php://input ``
or
``Warning: filesize(): stat failed for php://input in \vendor\respect\validation\library\Rules\Size.php on line 110``
``Fatal error: Uncaught RuntimeException: Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?``

It would be nice to add PSR7 StreamInterface support.

**Comment by raheelkhan** [comment]
@henriquemoody I was thinking to detect that if the user has supplied `php://input` instead of filename, we can detect that and do the `file_get_contents('php://input')` to get the body of stream as string. However, If I try to return the `strlen` of string it would return number of bytes considering the encoding is ASCII. But it will not work if there are some non ascii characters that could take multiple bytes per character. Any suggestions ?  Thanks

**Comment by henriquemoody** [comment]
With so many open issues, it's become hard to really know what's really important and what I have fixed already.

I'm closing issues that are too old, and I'm not really looking at them all. If this is still relevant, please comment here and I will reopen this issue.

Thanks for reporting! 🐼
