### ISSUE TITLE
Validate if there's a illegal attribute

### ISSUE THREAD

**Issue by christianmalek** [Respect/Validation#853]
I would like to have a validator which checks if an object has illegal attributes. So there is a defined set of attributes like `attributeA` and `attributeB` which are allowed. Some attributes are required and some are optional. All other attributes like `attributeRandomXY` should invalidate the validation. Is this possible?

Example:
```php
  $obj = new \stdClass();
  $obj->attributeA = 1; // required
  $obj->attributeB = 2; // required, but optional
  $obj->attributeWithUnknownName = false; // should fail the validation
```

**Comment by henriquemoody** [comment]
@christianmalek  I'm very sorry it took so long and you didn't get any reply on your issue. It sucks but sometimes it happens. I'm gonna close this issue because it's very old and I have reasons to believe that you've moved on.

I hope you found a resolve for your problem anyways, and feel free to open new ones at anytime and hopefully it will not take almost a year for somebody to reply! 🐼

**Comment by christianmalek** [comment]
@henriquemoody Thanks for your response. :)
