### ISSUE TITLE
Url validation error message grammatical issue

### ISSUE THREAD

**Issue by hpaknia** [Respect/Validation#856]
Url validation error states `an Url` which I believe should be `a URL`.

**Comment by henriquemoody** [comment]
That's fixed in master already (see [UrlException](https://github.com/Respect/Validation/blob/master/library/Exceptions/UrlException.php)).

I'm have to sleep a bit on it, but I think we can't release that in a patch version (see https://github.com/Respect/Validation/pull/1013#issuecomment-397730390)

**Comment by dmirogin** [comment]
Yeah, sure, some misunderstanding. So you should close this issue, i think.

**Comment by henriquemoody** [comment]
I think that makes sense, indeed. Thanks for reporting, @hpaknia, and thanks for the PR, @dmirogin! 🐼

**Comment by henriquemoody** [comment]
I decided to release that in version 1.1.19, please upgrade your version.

Thanks for reporting! 🐼
